version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_1903_AWSINTProject
  gitServerName: SIQA_kvv_ibm
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: SIQA_kvv_ibm
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_1903_awsint.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_1903_AWSINTProject
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: project.siqa_1903_awsint.integrations:Sum
  packages:
  - name: SIQA_1903_AWSINTProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: project.siqa_1903_awsint.integrations:deepclonetest
  packages:
  - name: SIQA_1903_AWSINTProject
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2040
